config/routes.rb
Rails.application.routes.draw do
 
  root to: "homes#top"
  devise_for :users
  get 'home/about',to:'pages#about'
  resources :books
  resources :users, only:[:index, :create, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books, dependent: :destroy
has_one_attached :profile_image

validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
validates :introduction, length: { maximum: 50 }


def get_profile_image(width, height)
  if profile_image.attached?
    profile_image.variant(resize_to_limit: [width, height]).processed
  else
    file_path = Rails.root.join('app/assets/images/sample-user1.jpg')
    self.profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    # flash[@notice] = "Signed out successfully."
    root_path
  end
  
  protected
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new(book_params)
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] ="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render 'books/index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    user = current_user
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book =Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end

    if @book.update(book_params)
      flash[:notice] ="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      # flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to root_path
    else
      render :new
    end
  end


  def index
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] ="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'users/edit'
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
<h2>User info</h2>

<div>
  <% if user.present? %>
  <% if user.profile_image.attached? %>
    <%= image_tag user.profile_image, size: "100x100" %>
  <% else %>
    <%= image_tag 'no_image', size: "100x100" %>
  <% end %>
</div>

<div>
<table class="table table-striped">
<thead>
  <tr>
    <th scope="col">name</th>
    <th scope="col"><%= user.name %></th>
  </tr>
</thead>
<tbody>
  <tr>
    <th scope="row">introduction</th>
    <th scope="row"><%= user.introduction %></th>
  </tr>
</tbody>
</table>

    <%= link_to edit_user_path(user) do %>
      <button type="button" class="btn btn-outline-secondary btn-block"><i class="fa-solid fa-user-gear"></i></button>
      </button>
    <% end %>
</div>  

<h2>New book</h2>

<%= form_with model: Book.new do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>

  <h5>Opinion</h5>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book' ,class:"btn btn-success" %>
<% end %>
<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
  <div class="col-md-3">
  <%= render 'info', user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Title</th>
        <th scope="col">Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <th scope="row"><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user.id) %></th>
        <th scope="row"><%= link_to book.title, book_path(book) %></th>
        <th scope="row"><%= book.body %></th>
      </tr>
      <% end %>
    </tbody>
    </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
  <div class="col-md-3">
  <%= render 'info', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h1>Book detail</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">
          <%= link_to user_path(@book.user.id) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %>
            <br>
            <%= @book.user.name %></th>
          <% end %>
        <th scope="col"><%= link_to @book.title, book_path(@book.id) %>
        <th scope="col"><%= @book.body %>
        <th scope="col"><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success " if @book.user == current_user %>
        <th scope="col"><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-sm btn-danger" if @book.user == current_user %>
      </tr>
    </thead>
  </table>  
</div>
</div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
  
<div class="text-center">
<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers!!</strong></h1>
<p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions,inpressions,and emotions.</p>
<p>about various books!</p>

<%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm mb-3" %><br>
<%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    

    <script src="https://kit.fontawesome.com/1a24d1deb3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg  bg-dark navbar-dark pt-1 pb-1">
        <div class="container">
        <a class="navbar-brand p-3" href="/">
          <p class="text-white">Bookers</p>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa-solid fa-house"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
              <i class="fa-solid fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path do %>
              <i class="fa-solid fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa-solid fa-right-from-bracket"></i> Log out
            <% end %>
          </li>
      <% else %>
        <ul>
        <li>
        <%= link_to root_path do %>
          <i class="fa-solid fa-house"></i> Home
        <% end %>
        </li>
        <li>
        <%= link_to home_about_path do %>
          <i class="fa-solid fa-link"></i> About
        <% end %>
        </li>
        <li>
        <%= link_to new_user_registration_path do %>
          <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>
        </li>
        <li>
        <%= link_to new_user_session_path do %>
          <i class="fa-solid fa-right-to-bracket"></i> Log in
        <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
</header>
    
<main class="mb-auto">
    <%= yield %>
</main>

<footer class="pt-5 pb-4">
  <div class="d-flex justify-content-center">
  <p>CopyRight Infratop.inc</p>
  </div>
</footer>
</body>
</html>

app/views/pages/about.html.erb
<div class="text-center">
<h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers!</strong></h1>
</div>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <p><label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></p>

  <p><label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> </p>
  
  <p><label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介"%></p>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-3">
  <%= render 'books/info', user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
  </tr>
  </thead>
<tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to image_tag user.get_profile_image(100,100) %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>  
  <% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/info', user: @user, book: @book %>
    </div>
  <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Title</th>
      <th scope="col">Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
      <th scope="row"><%= link_to image_tag @user.get_profile_image(100,100) %></th>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>